### ISSUE TITLE
Wireframing events UI

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#1]
We need a design for two pages

## Event List Page

- It should show all the events in a list format.
    - Date
    - Location
    - Comfirmed
    - Posted
    - Google form sent
- Clicking on an event should open the event details page.
- There should be a way to delete an event.

## Event Details Page

- It should display all the properties of the event.
- The user should be able to edit values of the properties.
- Edit button
- Save button
- Cancel button
- Delete button

**Comment by igMike-V** [comment]
Saved in Figma.

The single event edit page would be either a Modal or just, replace the view with a form and return to view on save or cancel. We can safely start with the list view and create some dummy data in a file in the shape we expect from the backend to populate the view.  This way we can unblock all the projects and get going on for the edit view I suggest we start with a single-column form and then add/refactor the styles in the next sprint.

**Comment by igMike-V** [comment]
added sketch for edit form on mobile only. The layout is designed with Flexbox in mind so I didn't bother with a desktop view of the form. I can add it later when we do an actual design layout

**Comment by igMike-V** [comment]
@parradaniela  I was going off signed-off tickets in Jira and didn't see your layout for the forms, Sorry about that.  

@0916dhkim  do you have an example of an "event type"

**Comment by igMike-V** [comment]
https://www.figma.com/proto/paJ2LeDmE7HI6mjf0L3gcg/EOT---Low-Fi-Wireframes?page-id=0%3A1&type=design&node-id=55-56&viewport=-670%2C-794%2C0.5&scaling=min-zoom&starting-point-node-id=55%3A56&show-proto-sidebar=1
