### ISSUE TITLE
Fix prettier scripts

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#145]
When we run `format:write` script in web module, it doesn't process all source files.
For example, `src/App.css` is processed but `src/Layout/RootLayout.tsx` is not. I suspect it is because of how prettier consumes the pattern `src/**/*.tsx`.

Let's fix the script to be similar to what's shown in the prettier installation guide ([link](https://prettier.io/docs/en/install.html)).
```
prettier . --check
```

**Comment by ThaungThanHan** [comment]
Hello. I would like to work on it.
