### ISSUE TITLE
Login & Signup Pages

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#190]
Build frontend pages for login & signup.
They should call the auth API from our backend and redirect users to the dashboard when successful.

**Comment by AbrarAlHasan** [comment]
I would Like to Work on this

**Comment by yugsharma1711** [comment]
I would want to work on it

**Comment by navdeep1840** [comment]
Hey, Can you assign this task to me ?

**Comment by 0916dhkim** [comment]
We are waiting for the design to be finalized
