### ISSUE TITLE
Set up a project structure for backend

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#3]
Tech stack
- Postgres
- Prisma
- Nest

**Comment by Jenna59** [comment]
Thurs. Jun. 1st: 
1.5hrs:
Installed PostgreSQL, pgAdmin, etc on local machine
Did beginner tutorial that went through creating a db 
Familiarized self with interface
Learned sudo command to kill server
