### ISSUE TITLE
Decide on the data schema

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#4]
We already have a draft [here](https://docs.google.com/document/d/1YN18ZGSZMXhZJcrxaBlKDWdJ0PicjDUK86woeh2J26I/edit?pli=1#heading=h.mggqn0ug537p)

Finalize db schema

Determine API request & response shapes.

**Comment by Jenna59** [comment]
@0916dhkim for finalize db schema, is it that you want me to go ahead in Postgres and start creating the tables? And for API request and response shapes, would it be something like what's in this doc: https://docs.beeswax.com/docs/api-requests-and-responses. Like, determine where we would need a message, an error message, etc? I'm familiar with res, req, next, I've just never heard the term request & response shapes. Would it be this: https://www.prisma.io/docs/concepts/components/prisma-schema? Thanks!

**Comment by Jenna59** [comment]
This is why I said I needed to read the docs! lol

**Comment by 0916dhkim** [comment]
@Jenna59 
About db schema, we don't need to create actual tables or write code at this point. Just an ERD or a written equivalent. What we have in the google doc looks sufficient tbh. We just need to add/remove some fields to match our wireframe.

By request & response shapes, I meant API specification. OpenAPI spec is most widely used ([documentation](https://swagger.io/docs/specification/basic-structure/)), but we don't need to be super formal at this point. Any format is okay as long as we know the shape of the data we pass into the API request, and the shape of the data that is returned as the API response.

**Comment by 0916dhkim** [comment]
The idea is to unblock people for UI & API implementation tasks. They need to know what kind of data they are dealing with before writing their code.

**Comment by Jenna59** [comment]
@0916dhkim do you want to take a look at this? https://www.figma.com/file/djA9GMoQoOJBSDaJZdWdDJ/Untitled?type=whiteboard&node-id=0-1&t=xLC7J5Jj5wWmGNu4-0

**Comment by 0916dhkim** [comment]
@Jenna59 Looking great! I'll go through the comments today.
In general, I think we should be able to remove the fields that are not immediately needed.

**Comment by 0916dhkim** [comment]
I reviewed the figma file 👍 
- There are some fields/tables we can remove for now. I think it will be simpler to start with a smaller schema.
- I think table names should be singular, following Prisma's naming convention.

**Comment by Jenna59** [comment]
@0916dhkim done. I was doing a SQL schema, hence the VARCHAR, etc. I think the last time I worked with SQL, I used Microsoft SQL server because the school had a deal with Microsoft. Postgres would be the actual db schema, no? And then Prisma would be the model and can do the introspective type mapping.

**Comment by Jenna59** [comment]
@0916dhkim also, I thought I asked you about this on Discord, but maybe I didn't or it got lost in the maelstrom. For the API schema shapes, are you looking to have those done in JSON? Or More of a use Figma/Google docs kind of thing?

**Comment by 0916dhkim** [comment]
@Jenna59 Awesome, I think we can remove "EVENT REGISTRATION COMPLETED" field from the user table and mark this issue as completed.

About Prisma, there are generally two ways to manage schema, depends on what we use as the source of truth.

1. Using `schema.prisma` file ([doc](https://www.prisma.io/docs/concepts/components/prisma-schema)). In this case, the source of truth is the `schema.prisma` file written in Prisma Schema Language. Prisma applies the schema to database through `prisma migrate deploy` command. To change the schema, we need to edit the `schema.prisma` file and deploy.
2. Using introspection ([doc](https://www.prisma.io/docs/concepts/components/introspection)). The database is the source of truth. Prisma generates data models from existing database through `prisma db pull` command. To change the schema, we need to run SQL migration on the database and run `prisma db pull`.

I prefer using the first approach because it fits well with a CI/CD pipeline. We can run `prisma migrate deploy` in CI script. On the other hand, it will be a little unclear when to run `prisma db pull` if we use introspection.

**Comment by 0916dhkim** [comment]
> are you looking to have those done in JSON? Or More of a use Figma/Google docs kind of thing?

@Jenna59 You can post example JSONs in this issue :+1:

**Comment by Jenna59** [comment]
> are you looking to have those done in JSON? Or More of a use Figma/Google docs kind of thing?

Cool. I'll probably do it tomorrow morning. I've been trying to take it a bit easier and recalibrate this weekend. I'll have stuff for you by Stand Up on Monday, for sure.

**Comment by 0916dhkim** [comment]
Sounds good!

**Comment by Jenna59** [comment]
@0916dhkim Hi Danny, I'm not sure how to get the parse error on line 38 to go away. Tried everything I could think of. Also, do we need the EventType table? Or was that subsumed under events? Not sure if I put the right urls or did the content part right. Also for the routes, I just left them as "event" and "user" because idk what the FE wants to build out. We could presumably modify them to "eventcreate", "eventdelete", etc. I made everything arrays of strings. 

[api-structure.json.zip](https://github.com/EOT-Event-Organizer-s-Toolbox/eot-codebase/files/11647406/api-structure.json.zip)

**Comment by Jenna59** [comment]
^ or was I supposed to list the type of every piece of data in the table?

**Comment by 0916dhkim** [comment]
@Jenna59 
- I think the error happens because `.json` file only expects 1 object in it. It is an invalid syntax to list multiple objects in a single json file. You can just copy-paste the whole JSON as a text in this thread.
- Yes, we need an EventType table because we need to be able to create/delete event types on demand. Can't do it if it is a string field under Event table. We can flatten it when we return data from API endpoint tho. DB schema doesn't need to 100% match the response shape.
- If we want to go with OpenAPI specs, we should make the schema more specific. But I'm okay with just using dummy data as I said before.

OpenAPI schema example:
```json
"schema": {
  "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "type": { "type": "string" },
        "ideaConfirmed": { "type": "boolean" },
        "volunteersNeeded": { "type": "integer" },
        ...
      }
    }
}
```
Dummy data example:
```json
{
  "id": "abcdefg",
  "type": "In-Person Social",
  "ideaConfirmed": false,
  "volunteersNeeded": 5,
  ...
}
```

**Comment by Jenna59** [comment]
yeah, I kind of thought that was the JSON issue, but I also didn't want to dump a huge JSON file into the GitHub thread.
