### ISSUE TITLE
CONTRIBUTING.md First Draft

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#46]
- Move "Getting Started" section from `README.md` to `CONTRIBUTING.md`.
- Add the following links to the `CONTRIBUTING.md` file:
    - The master google docs
    - DB schema figma
    - Wireframe figma

Example `CONTRIBUTING.md` file from Storybook: https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md

**Comment by igMike-V** [comment]
@semsi-dogruer  this is a good ticket for you for practice forking the repo and doing a PR

**Comment by semsi-dogruer** [comment]
@igMike-V I agree:) Thanks.
