### ISSUE TITLE
Backend tech stack migration

### ISSUE THREAD

**Issue by 0916dhkim** [EOT-Event-Organizer-s-Toolbox/eot-codebase#53]
Migrate from nestjs to expressjs.

- Remove everything inside `/server` except `/server/prisma`.
- Install expressjs + typescript + @types/express
- Write the base code for starting the express server.

**Comment by one2code** [comment]
@0916dhkim I've removed all Nest related dependencies, including the Jest test dependencies and scripts, and installed Express. I just wanted to verify if we would be using rxjs anywhere in the project? I do not believe we have a need for this package with an Express installation. This comment on the Express framework page pretty much reaffirms that position [https://github.com/expressjs/express/issues/4362](url).

If so, I will remove this dependency tomorrow.

**Comment by 0916dhkim** [comment]
@one2code Yes, let's remove rxjs too :+1:

**Comment by DaleOrders** [comment]
Sorry I'm just seeing this for the first time. Are we no longer using nestjs?

**Comment by 0916dhkim** [comment]
@DaleOrders Yes, we decided to use expressjs instead of nestjs because it will be simpler to learn 👍

**Comment by one2code** [comment]
@daleorders, it's almost done. I've removed the src files and what I
believe have been the nest related packages with npm uninstall --save dev.
Got an error to source in tsconfig.json (i think it is related to the last
file I deleted), then I will setup an index.ts for Express and test out the
server.

I think we can still move forward with the original TS and Prettier
installations. Will see tonight when I get home from work.

**Comment by one2code** [comment]
@0916dhkim @DaleOrders 

I'm probably going to have to bring this to code club tomorrow (I won't have more time till tomorrow afternoon). I tried to manually configure everything during the migration, instead of doing a mass delete. Seems like I did something wrong with the tsc setup, and it's not recognizing the ts extension when I run index.ts with dummy text.

> server@0.0.1 start
> ts-node src/index.ts
`
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/one2code/EOT/eot-codebase/server/src/index.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
`
Here is what the tsconfig.json looks like atm.
`{
  "compilerOptions": {
    "module": "CommonJS",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  },
  "include": ["src/**/*.ts","src/index.ts"],
}
`

**Comment by DaleOrders** [comment]
@one2code Were you able to fix it? Or do you need some help?

**Comment by one2code** [comment]
Should be good now! It was the "type:" "module" key-value in the
tsconfig.json. Was a great learning experience! I'm happy I went with a
step-by-step migration vs the nuclear option. I would have never
encountered this problem if I started from scratch.
